name: "grenade-brothers-build"
steps:
  - label: buildah login
    script:
      path: "../common/buildah-login.sh"
  - label: git clone
    script:
      path: "../common/git-clone.sh"
      arguments:
        - "https://git.adyxax.org/adyxax/grenade-brothers"
  - label: build image
    script:
      path: "build-image.sh"
  - label: make push
    script:
      path: "../common/make.sh"
      arguments:
        - "push"
  - label: clean
    script:
      path: "../common/clean.sh"
identities:
  - quay-io
runner:
  identity: "ssh-myth"
  name: "ssh"
  parameters:
    host: "myth.adyxax.org"
    user: "root"
